// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcGearHub.Data.DBModels;

public partial class Order
{
    public int OrderId { get; set; }

    public int? UserId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Status { get; set; }

    public decimal TotalAmount { get; set; }

    public int? OrderAddress { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CreatedUser { get; set; }

    public string UpdatedUser { get; set; }

    public virtual Address OrderAddressNavigation { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }
}