// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcGearHub.Data.DBModels;

public partial class OrderItem
{
    public int OrderItemId { get; set; }

    public int? OrderId { get; set; }

    public int? ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CreatedUser { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedUser { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}