// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcGearHub.Data.DBModels;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? OrderId { get; set; }

    public DateTime? PaymentDate { get; set; }

    public decimal Amount { get; set; }

    public string PaymentStatus { get; set; }

    public int? PaymentMethodId { get; set; }

    public string CreatedUser { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedUser { get; set; }

    public virtual Order Order { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }
}