// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcGearHub.Data.DBModels;

public partial class Permission
{
    public int PermissionId { get; set; }

    public string PermissionName { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CreatedUser { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedUser { get; set; }

    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
}